on:
  push:
    tags:        
      - 'v*'

name: Release

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build
        run: |
          GO_ENABLE=0 go build -ldflags '-extldflags "-static"' -tags timetzdata

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: immich-stacker
